Repository puppetlabs/puppet-module-gems, pull requests merged in 2020-11, with the labels that each got.

#145 Pin rspec-expectations
  config/dependencies.yml
Labels: bug

#146 Release-prep for v0.5.2
  CHANGELOG.md
  config/info.yml
Labels: maintenance

#147 fixup push-gems script
  exe/push-gems.rb
Labels: enhancement

#148 Pin parallel to < 1.20 on ruby 2.4, since 1.20 requires ruby 2.5
  config/dependencies.yml
Labels: enhancement

#149 Allow rspec-puppet-facts v2
  config/dependencies.yml
Labels: enhancement

#151 Remove rspec-expectations pin
  config/dependencies.yml
Labels: bug

#152 Release-prep v0.5.3
  CHANGELOG.md
  config/info.yml
Labels: maintenance

#153 (IAC-1233) Remove litmus as a dependency in Ruby 2.5 & 2.6
  config/dependencies.yml
Labels: enhancement, maintenance

#155 Update metadata-json-lint pin to allow 3.x release train
  config/dependencies.yml
Labels: enhancement
